import 'dotenv/config'
import { Pool } from "pg"
import { PrismaClient, PlaceStatus } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import bcrypt from 'bcryptjs'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

async function main() {
  const passwordHash = await bcrypt.hash('admin123', 10)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@ngopidi.cafe' },
    update: {},
    create: {
      email: 'admin@ngopidi.cafe',
      name: 'Admin User',
      password: passwordHash,
      role: 'ADMIN',
    },
  })
  console.log({ admin })

  const passwordHash2 = await bcrypt.hash('user123', 10)
  const user = await prisma.user.upsert({
    where: { email: 'user@ngopidi.cafe' },
    update: {},
    create: {
      email: 'user@ngopidi.cafe',
      name: 'Regular User',
      password: passwordHash2,
      role: 'USER',
    },
  })
  console.log({ user })

  const coffeeShops = [
    {
      name: "Anomali Coffee Senopati",
      address: "Jl. Senopati No.19, Jakarta Selatan",
      latitude: -6.2349,
      longitude: 106.8095,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Giyanti Coffee Roastery",
      address: "Jl. Surabaya No.20, Menteng, Jakarta Pusat",
      latitude: -6.1856,
      longitude: 106.8329,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Tanamera Coffee Thamrin",
      address: "Thamrin City, Jakarta Pusat",
      latitude: -6.1979,
      longitude: 106.8228,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "1/15 Coffee Gandaria",
      address: "Jl. Gandaria I No.63, Jakarta Selatan",
      latitude: -6.2435,
      longitude: 106.7865,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Common Grounds Sudirman",
      address: "CityWalk Sudirman, Jakarta Pusat",
      latitude: -6.2151,
      longitude: 106.8166,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Blue Doors",
      address: "Jl. Alkateri No.2, Bandung",
      latitude: -6.9213,
      longitude: 107.6071,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Armor Kopi",
      address: "Jl. Bukit Pakar Utara No.10, Bandung",
      latitude: -6.8524,
      longitude: 107.6321,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Mimiti Coffee & Space",
      address: "Jl. Sumur Bandung No.14, Bandung",
      latitude: -6.8906,
      longitude: 107.6105,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Two Hands Full",
      address: "Jl. Sukajadi No.198, Bandung",
      latitude: -6.8831,
      longitude: 107.5956,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Sejiwa Coffee",
      address: "Jl. Progo No.15, Bandung",
      latitude: -6.9038,
      longitude: 107.6162,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Noah's Barn",
      address: "Jl. Dayang Sumbi No.2, Bandung",
      latitude: -6.8879,
      longitude: 107.6136,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Lacamera Coffee",
      address: "Jl. Naripan No.99, Bandung",
      latitude: -6.9198,
      longitude: 107.6165,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Wiki Koffie",
      address: "Jl. Braga No.90, Bandung",
      latitude: -6.9174,
      longitude: 107.6094,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Braga Art Cafe",
      address: "Jl. Braga No.68, Bandung",
      latitude: -6.9179,
      longitude: 107.6094,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Sydwic",
      address: "Jl. Cilaki No.63, Bandung",
      latitude: -6.9011,
      longitude: 107.6225,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kurokoffee",
      address: "Jl. Ciumbuleuit No.130, Bandung",
      latitude: -6.8774,
      longitude: 107.6045,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Contrast Coffee",
      address: "Jl. Anggrek No.12, Bandung",
      latitude: -6.9125,
      longitude: 107.6231,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Wheels Coffee Roasters",
      address: "Jl. Prof. Eyckman No.32, Bandung",
      latitude: -6.8965,
      longitude: 107.6012,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Morgy Coffee",
      address: "Jl. Anggrek No.46, Bandung",
      latitude: -6.9138,
      longitude: 107.6254,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kinokimi Coffee",
      address: "Jl. Buah Batu No.132, Bandung",
      latitude: -6.9365,
      longitude: 107.6234,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Discourse Coffee",
      address: "Jl. Dr. Setiabudi No.56, Bandung",
      latitude: -6.8765,
      longitude: 107.5943,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Haloka",
      address: "Jl. Veteran No.7, Bandung",
      latitude: -6.9187,
      longitude: 107.6145,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kozi Coffee",
      address: "Jl. Gudang Selatan No.22, Bandung",
      latitude: -6.9156,
      longitude: 107.6267,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Teduh Coffee",
      address: "Jl. Pinus No.62, Bandung",
      latitude: -6.8943,
      longitude: 107.6345,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Sawo Coffee",
      address: "Jl. Braga No.7, Bandung",
      latitude: -6.9189,
      longitude: 107.6102,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "One Eighty Coffee and Music",
      address: "Jl. Ganesha No.3, Bandung",
      latitude: -6.8913,
      longitude: 107.6105,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Hummingbird Eatery & Space",
      address: "Jl. Progo No.14, Bandung",
      latitude: -6.9039,
      longitude: 107.6164,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kopi Toko Djawa (Braga)",
      address: "Jl. Braga No.81, Bandung",
      latitude: -6.9174,
      longitude: 107.6096,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kopi Toko Djawa (Gandapura)",
      address: "Jl. Gandapura No.61, Bandung",
      latitude: -6.9142,
      longitude: 107.6221,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Jurnalrisa Coffee",
      address: "Jl. Braga No.45, Bandung",
      latitude: -6.9182,
      longitude: 107.6092,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Cups Coffee & Kitchen",
      address: "Jl. Trunojoyo No.25, Bandung",
      latitude: -6.9032,
      longitude: 107.6141,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Sini Kopi",
      address: "Jl. Pelajar Pejuang 45 No.62, Bandung",
      latitude: -6.9324,
      longitude: 107.6256,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Jardin Cafe",
      address: "Jl. Cimanuk No.1A, Bandung",
      latitude: -6.9056,
      longitude: 107.6189,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Miss Bee Providore",
      address: "Jl. Rancabentang No.11A, Bandung",
      latitude: -6.8778,
      longitude: 107.6042,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kalpa Tree Dine and Chill",
      address: "Jl. Kiputih No.37, Bandung",
      latitude: -6.8654,
      longitude: 107.6221,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Orofi Cafe",
      address: "Jl. Lembah Pakar Timur No.99, Bandung",
      latitude: -6.8521,
      longitude: 107.6365,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Congo Gallery & Resto",
      address: "Jl. Rancabentang No.98, Bandung",
      latitude: -6.8754,
      longitude: 107.6067,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Warung Kopi Imah Babaturan",
      address: "Jl. Kebon Bibit No.3, Bandung",
      latitude: -6.8967,
      longitude: 107.6089,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Makmur Jaya Coffee Roaster",
      address: "Jl. Lengkong Besar No.62, Bandung",
      latitude: -6.9245,
      longitude: 107.6123,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Halu Coffee",
      address: "Jl. Sabang No.17, Bandung",
      latitude: -6.9123,
      longitude: 107.6187,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kopi Selamat Pagi",
      address: "Jl. Cimanuk No.31, Bandung",
      latitude: -6.9045,
      longitude: 107.6198,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kiputih Satu Bake & Dine",
      address: "Jl. Kiputih No.1, Bandung",
      latitude: -6.8678,
      longitude: 107.6212,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Marka Coffee & Kitchen",
      address: "Jl. Talaga Bodas No.32, Bandung",
      latitude: -6.9312,
      longitude: 107.6211,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kyomi Space",
      address: "Jl. Ir. H. Juanda No.420, Bandung",
      latitude: -6.8745,
      longitude: 107.6189,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Mana Bandung",
      address: "Jl. Cibengang No.17, Bandung",
      latitude: -6.8532,
      longitude: 107.6211,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "150 Coffee and Garden",
      address: "Jl. Sulaksana No.50, Bandung",
      latitude: -6.9121,
      longitude: 107.6543,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Coffee and John",
      address: "Jl. Naripan No.1, Bandung",
      latitude: -6.9211,
      longitude: 107.6089,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kopi Bawah Tangga",
      address: "Paris Van Java, Bandung",
      latitude: -6.8899,
      longitude: 107.5956,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Dr. Ells Coffee",
      address: "Jl. Majalaya No.22, Bandung",
      latitude: -6.9012,
      longitude: 107.6211,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Blue Lane Coffee",
      address: "Jl. Lembong No.8, Bandung",
      latitude: -6.9189,
      longitude: 107.6111,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Kopi Kisah Manis",
      address: "Jl. Abdul Majid No.1, Bandung",
      latitude: -6.9122,
      longitude: 107.6321,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Habitaas",
      address: "Jl. Raden Patah No.3, Bandung",
      latitude: -6.8912,
      longitude: 107.6156,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Little Contrast",
      address: "Jl. Braga No.33, Bandung",
      latitude: -6.9178,
      longitude: 107.6091,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Toko Kopi Jaya",
      address: "Jl. Pajajaran No.81, Bandung",
      latitude: -6.9011,
      longitude: 107.5945,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
    {
      name: "Morning Glory Coffee",
      address: "Setrasari Mall, Bandung",
      latitude: -6.8789,
      longitude: 107.5876,
      wifiAvailable: true,
      wifiSpeed: 0,
      status: "UNVERIFIED" as PlaceStatus,
      priceLevel: 0,
      wifiStability: 'good' as const,
      crowdLevel: 'normal' as const,
    },
  ]

  for (const shop of coffeeShops) {
    const existing = await prisma.place.findFirst({
      where: { name: shop.name }
    })

    if (!existing) {
      await prisma.place.create({
        data: shop
      })
      console.log(`Created place: ${shop.name}`)
    } else {
      console.log(`Place already exists: ${shop.name}`)
    }
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
