import { PrismaPg } from '@prisma/adapter-pg'
import {
    CommonVisitor,
    CrowdLevel,
    MusicVolume,
    NoiseLevel,
    OutletDensity,
    PlaceStatus,
    PrismaClient,
    SeatingType,
    SmokingArea,
    StayPolicy,
    TableSize,
    TemperatureComfort,
    WifiPolicy,
    WifiStability,
} from '@prisma/client'
import bcrypt from 'bcryptjs'
import 'dotenv/config'
import crypto from 'node:crypto'
import { Pool } from 'pg'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

async function main() {
    const passwordHash = await bcrypt.hash('admin1234', 10)
    const admin = await prisma.user.upsert({
        where: { email: 'admin@ngopidi.cafe' },
        update: {},
        create: {
            id: crypto.randomUUID(),
            email: 'admin@ngopidi.cafe',
            name: 'Admin User',
            password: passwordHash,
            role: 'ADMIN',
            email_verified: new Date(),
        },
    })
    console.log({ admin })

    const passwordHash2 = await bcrypt.hash('user1234', 10)
    const user = await prisma.user.upsert({
        where: { email: 'user@ngopidi.cafe' },
        update: {},
        create: {
            id: crypto.randomUUID(),
            email: 'user@ngopidi.cafe',
            name: 'Regular User',
            password: passwordHash2,
            role: 'USER',
            email_verified: new Date(),
        },
    })
    console.log({ user })

    const coffeeShops = [
        {
            name: 'Anomali Coffee Senopati',
            address: 'Jl. Senopati No.19, Jakarta Selatan',
            latitude: -6.2349,
            longitude: 106.8095,
            wifi_available: true,
            wifi_speed: 45,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: true,
            work_friendly_score: 4.8,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: 'Giyanti Coffee Roastery',
            address: 'Jl. Surabaya No.20, Menteng, Jakarta Pusat',
            latitude: -6.1856,
            longitude: 106.8329,
            wifi_available: true,
            wifi_speed: 25,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 4,
            wifi_stability: 'average' as WifiStability,
            wifi_policy: 'purchase_required' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'few' as OutletDensity,
            table_size: 'small' as TableSize,
            noise_level: 'quiet' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'crowded' as CrowdLevel,
            laptop_friendly: false,
            stay_policy: 'soft_limit' as StayPolicy,
            meeting_friendly: false,
            call_friendly: false,
            work_friendly_score: 3.2,
            air_conditioning: true,
            restroom_available: true,
            parking_available: false,
        },
        {
            name: 'Tanamera Coffee Thamrin',
            address: 'Thamrin City, Jakarta Pusat',
            latitude: -6.1979,
            longitude: 106.8228,
            wifi_available: true,
            wifi_speed: 60,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'noisy' as NoiseLevel,
            music_volume: 'medium' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: true,
            work_friendly_score: 4.2,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: '1/15 Coffee Gandaria',
            address: 'Jl. Gandaria I No.63, Jakarta Selatan',
            latitude: -6.2435,
            longitude: 106.7865,
            wifi_available: true,
            wifi_speed: 35,
            status: 'UNVERIFIED' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'large' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: false,
            work_friendly_score: 4.5,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: 'Common Grounds Sudirman',
            address: 'CityWalk Sudirman, Jakarta Pusat',
            latitude: -6.2151,
            longitude: 106.8166,
            wifi_available: true,
            wifi_speed: 80,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'medium' as MusicVolume,
            crowd_level: 'crowded' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'soft_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: true,
            work_friendly_score: 4.7,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: 'Blue Doors',
            address: 'Jl. Alkateri No.2, Bandung',
            latitude: -6.9213,
            longitude: 107.6071,
            wifi_available: true,
            wifi_speed: 40,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 2,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'small' as TableSize,
            noise_level: 'quiet' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: false,
            call_friendly: true,
            work_friendly_score: 4.3,
            air_conditioning: false,
            restroom_available: true,
            parking_available: false,
        },
        {
            name: 'Armor Kopi',
            address: 'Jl. Bukit Pakar Utara No.10, Bandung',
            latitude: -6.8524,
            longitude: 107.6321,
            wifi_available: false,
            wifi_speed: 0,
            status: 'UNVERIFIED' as PlaceStatus,
            price_level: 2,
            wifi_stability: 'good' as WifiStability,
            power_outlets_available: false,
            table_size: 'large' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'crowded' as CrowdLevel,
            laptop_friendly: false,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: true,
            work_friendly_score: 2.5,
            air_conditioning: false,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: 'Mimiti Coffee & Space',
            address: 'Jl. Sumur Bandung No.14, Bandung',
            latitude: -6.8906,
            longitude: 107.6105,
            wifi_available: true,
            wifi_speed: 50,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'medium' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: true,
            work_friendly_score: 4.9,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: 'Two Hands Full',
            address: 'Jl. Sukajadi No.198, Bandung',
            latitude: -6.8831,
            longitude: 107.5956,
            wifi_available: true,
            wifi_speed: 30,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'noisy' as NoiseLevel,
            music_volume: 'medium' as MusicVolume,
            crowd_level: 'crowded' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'soft_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: false,
            work_friendly_score: 3.8,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: 'Sejiwa Coffee',
            address: 'Jl. Progo No.15, Bandung',
            latitude: -6.9038,
            longitude: 107.6162,
            wifi_available: true,
            wifi_speed: 55,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            call_friendly: true,
            work_friendly_score: 4.8,
            air_conditioning: true,
            restroom_available: true,
            parking_available: true,
        },
        {
            name: "Noah's Barn",
            address: 'Jl. Dayang Sumbi No.2, Bandung',
            latitude: -6.8879,
            longitude: 107.6136,
            wifi_available: true,
            wifi_speed: 40,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            meeting_friendly: true,
            work_friendly_score: 4.4,
            air_conditioning: true,
        },
        {
            name: 'Lacamera Coffee',
            address: 'Jl. Naripan No.99, Bandung',
            latitude: -6.9198,
            longitude: 107.6165,
            wifi_available: true,
            wifi_speed: 35,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 2,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 4.2,
            air_conditioning: true,
        },
        {
            name: 'Wiki Koffie',
            address: 'Jl. Braga No.90, Bandung',
            latitude: -6.9174,
            longitude: 107.6094,
            wifi_available: true,
            wifi_speed: 25,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 1,
            wifi_stability: 'average' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'few' as OutletDensity,
            table_size: 'small' as TableSize,
            noise_level: 'noisy' as NoiseLevel,
            crowd_level: 'crowded' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 3.5,
            air_conditioning: false,
        },
        {
            name: 'Braga Art Cafe',
            address: 'Jl. Braga No.68, Bandung',
            latitude: -6.9179,
            longitude: 107.6094,
            wifi_available: true,
            wifi_speed: 30,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'purchase_required' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'quiet' as NoiseLevel,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 4.1,
            air_conditioning: true,
        },
        {
            name: 'Sydwic',
            address: 'Jl. Cilaki No.63, Bandung',
            latitude: -6.9011,
            longitude: 107.6225,
            wifi_available: true,
            wifi_speed: 45,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 4.7,
            air_conditioning: true,
        },
        {
            name: 'Kurokoffee',
            address: 'Jl. Ciumbuleuit No.130, Bandung',
            latitude: -6.8774,
            longitude: 107.6045,
            wifi_available: true,
            wifi_speed: 35,
            status: 'VERIFIED_USER' as PlaceStatus,
            price_level: 2,
            wifi_stability: 'good' as WifiStability,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'quiet' as NoiseLevel,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 4.5,
            air_conditioning: false,
        },
        {
            name: 'Contrast Coffee',
            address: 'Jl. Anggrek No.12, Bandung',
            latitude: -6.9125,
            longitude: 107.6231,
            wifi_available: true,
            wifi_speed: 50,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'large' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 4.9,
            air_conditioning: true,
        },
        {
            name: 'Wheels Coffee Roasters',
            address: 'Jl. Prof. Eyckman No.32, Bandung',
            latitude: -6.8965,
            longitude: 107.6012,
            wifi_available: true,
            wifi_speed: 55,
            status: 'VERIFIED_ADMIN' as PlaceStatus,
            price_level: 3,
            wifi_stability: 'excellent' as WifiStability,
            power_outlets_available: true,
            power_outlet_density: 'many' as OutletDensity,
            table_size: 'large' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            crowd_level: 'crowded' as CrowdLevel,
            laptop_friendly: true,
            work_friendly_score: 4.8,
            air_conditioning: true,
        },
        // The rest of the places will use default random diversification in the seed script
        ...[
            { name: 'Morgy Coffee', address: 'Jl. Anggrek No.46, Bandung', lat: -6.9138, lng: 107.6254 },
            { name: 'Kinokimi Coffee', address: 'Jl. Buah Batu No.132, Bandung', lat: -6.9365, lng: 107.6234 },
            { name: 'Discourse Coffee', address: 'Jl. Dr. Setiabudi No.56, Bandung', lat: -6.8765, lng: 107.5943 },
            { name: 'Haloka', address: 'Jl. Veteran No.7, Bandung', lat: -6.9187, lng: 107.6145 },
            { name: 'Kozi Coffee', address: 'Jl. Gudang Selatan No.22, Bandung', lat: -6.9156, lng: 107.6267 },
            { name: 'Teduh Coffee', address: 'Jl. Pinus No.62, Bandung', lat: -6.8943, lng: 107.6345 },
            { name: 'Sawo Coffee', address: 'Jl. Braga No.7, Bandung', lat: -6.9189, lng: 107.6102 },
            { name: 'One Eighty Coffee and Music', address: 'Jl. Ganesha No.3, Bandung', lat: -6.8913, lng: 107.6105 },
            { name: 'Hummingbird Eatery & Space', address: 'Jl. Progo No.14, Bandung', lat: -6.9039, lng: 107.6164 },
            { name: 'Kopi Toko Djawa (Braga)', address: 'Jl. Braga No.81, Bandung', lat: -6.9174, lng: 107.6096 },
            {
                name: 'Kopi Toko Djawa (Gandapura)',
                address: 'Jl. Gandapura No.61, Bandung',
                lat: -6.9142,
                lng: 107.6221,
            },
            { name: 'Jurnalrisa Coffee', address: 'Jl. Braga No.45, Bandung', lat: -6.9182, lng: 107.6092 },
            { name: 'Cups Coffee & Kitchen', address: 'Jl. Trunojoyo No.25, Bandung', lat: -6.9032, lng: 107.6141 },
            { name: 'Sini Kopi', address: 'Jl. Pelajar Pejuang 45 No.62, Bandung', lat: -6.9324, lng: 107.6256 },
            { name: 'Jardin Cafe', address: 'Jl. Cimanuk No.1A, Bandung', lat: -6.9056, lng: 107.6189 },
            { name: 'Miss Bee Providore', address: 'Jl. Rancabentang No.11A, Bandung', lat: -6.8778, lng: 107.6042 },
            { name: 'Kalpa Tree Dine and Chill', address: 'Jl. Kiputih No.37, Bandung', lat: -6.8654, lng: 107.6221 },
            { name: 'Orofi Cafe', address: 'Jl. Lembah Pakar Timur No.99, Bandung', lat: -6.8521, lng: 107.6365 },
            { name: 'Congo Gallery & Resto', address: 'Jl. Rancabentang No.98, Bandung', lat: -6.8754, lng: 107.6067 },
            {
                name: 'Warung Kopi Imah Babaturan',
                address: 'Jl. Kebon Bibit No.3, Bandung',
                lat: -6.8967,
                lng: 107.6089,
            },
            {
                name: 'Makmur Jaya Coffee Roaster',
                address: 'Jl. Lengkong Besar No.62, Bandung',
                lat: -6.9245,
                lng: 107.6123,
            },
            { name: 'Halu Coffee', address: 'Jl. Sabang No.17, Bandung', lat: -6.9123, lng: 107.6187 },
            { name: 'Kopi Selamat Pagi', address: 'Jl. Cimanuk No.31, Bandung', lat: -6.9045, lng: 107.6198 },
            { name: 'Kiputih Satu Bake & Dine', address: 'Jl. Kiputih No.1, Bandung', lat: -6.8678, lng: 107.6212 },
            { name: 'Marka Coffee & Kitchen', address: 'Jl. Talaga Bodas No.32, Bandung', lat: -6.9312, lng: 107.6211 },
            { name: 'Kyomi Space', address: 'Jl. Ir. H. Juanda No.420, Bandung', lat: -6.8745, lng: 107.6189 },
            { name: 'Mana Bandung', address: 'Jl. Cibengang No.17, Bandung', lat: -6.8532, lng: 107.6211 },
            { name: '150 Coffee and Garden', address: 'Jl. Sulaksana No.50, Bandung', lat: -6.9121, lng: 107.6543 },
            { name: 'Coffee and John', address: 'Jl. Naripan No.1, Bandung', lat: -6.9211, lng: 107.6089 },
            { name: 'Kopi Bawah Tangga', address: 'Paris Van Java, Bandung', lat: -6.8899, lng: 107.5956 },
            { name: 'Dr. Ells Coffee', address: 'Jl. Majalaya No.22, Bandung', lat: -6.9012, lng: 107.6211 },
            { name: 'Blue Lane Coffee', address: 'Jl. Lembong No.8, Bandung', lat: -6.9189, lng: 107.6111 },
            { name: 'Kopi Kisah Manis', address: 'Jl. Abdul Majid No.1, Bandung', lat: -6.9122, lng: 107.6321 },
            { name: 'Habitaas', address: 'Jl. Raden Patah No.3, Bandung', lat: -6.8912, lng: 107.6156 },
            { name: 'Little Contrast', address: 'Jl. Braga No.33, Bandung', lat: -6.9178, lng: 107.6091 },
            { name: 'Toko Kopi Jaya', address: 'Jl. Pajajaran No.81, Bandung', lat: -6.9011, lng: 107.5945 },
            { name: 'Morning Glory Coffee', address: 'Setrasari Mall, Bandung', lat: -6.8789, lng: 107.5876 },
        ].map((p) => ({
            name: p.name,
            address: p.address,
            latitude: p.lat,
            longitude: p.lng,
            wifi_available: true,
            wifi_speed: 20 + Math.floor(Math.random() * 40),
            status: 'UNVERIFIED' as PlaceStatus,
            price_level: 2,
            wifi_stability: 'good' as WifiStability,
            wifi_policy: 'free' as WifiPolicy,
            power_outlets_available: true,
            power_outlet_density: 'moderate' as OutletDensity,
            table_size: 'medium' as TableSize,
            noise_level: 'moderate' as NoiseLevel,
            music_volume: 'low' as MusicVolume,
            crowd_level: 'normal' as CrowdLevel,
            laptop_friendly: true,
            stay_policy: 'no_limit' as StayPolicy,
            work_friendly_score: Number((3.5 + Math.random() * 1.5).toFixed(1)),
            air_conditioning: true,
        })),
    ]

    for (const shop of coffeeShops) {
        const existing = await prisma.place.findFirst({
            where: { name: shop.name },
        })

        if (!existing) {
            await prisma.place.create({
                data: {
                    ...shop,
                    submitter_id: admin.id,
                },
            })
            console.log(`Created place: ${shop.name}`)
        } else {
            console.log(`Place already exists: ${shop.name}`)
        }
    }
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
